version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.2
    steps:
      - checkout
      - run:
          command: |
            sudo pip install -r requirements.txt
      - run:
          command: |
           cd xtractor
           python -m unittest TopicExtractorTest.py
